// <auto-generated />
using System;
using DocSequence.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DocSequence.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260929224707_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DocSequence.Api.Entities.DocumentType", b =>
                {
                    b.Property<int>("DocumentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentTypeId"));

                    b.Property<long>("CurrentNumber")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("DocumentTypeId");

                    b.HasIndex("Prefix")
                        .IsUnique()
                        .HasDatabaseName("UX_DocumentTypes_Prefix");

                    b.ToTable("DocumentTypes", null, t =>
                        {
                            t.HasCheckConstraint("CK_DocumentTypes_CurrentNumber", "CurrentNumber >= 0");

                            t.HasCheckConstraint("CK_DocumentTypes_Prefix", "Prefix COLLATE Latin1_General_BIN2 NOT LIKE '%[^A-Z]%' AND LEN(Prefix) BETWEEN 2 AND 5");
                        });

                    b.HasData(
                        new
                        {
                            DocumentTypeId = 1,
                            CurrentNumber = 10428L,
                            IsActive = true,
                            Name = "CXY Drawing",
                            Prefix = "CXY",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DocumentTypeId = 2,
                            CurrentNumber = 10428L,
                            IsActive = true,
                            Name = "PXY Drawing",
                            Prefix = "PXY",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("DocSequence.Api.Entities.GeneratedDocument", b =>
                {
                    b.Property<long>("GeneratedDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("GeneratedDocumentId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("EngineerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<long>("Number")
                        .HasColumnType("bigint");

                    b.Property<Guid>("RequestKey")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GeneratedDocumentId");

                    b.HasIndex("Identifier")
                        .IsUnique()
                        .HasDatabaseName("UX_GeneratedDocuments_Identifier");

                    b.HasIndex("RequestKey")
                        .IsUnique()
                        .HasDatabaseName("UX_GeneratedDocuments_RequestKey");

                    b.HasIndex("CreatedAt", "GeneratedDocumentId")
                        .IsDescending()
                        .HasDatabaseName("IX_GeneratedDocuments_CreatedAt");

                    b.HasIndex("DocumentTypeId", "Number")
                        .IsUnique()
                        .HasDatabaseName("UX_GeneratedDocuments_DocumentTypeId_Number");

                    b.ToTable("GeneratedDocuments", (string)null);
                });

            modelBuilder.Entity("DocSequence.Api.Entities.GeneratedDocument", b =>
                {
                    b.HasOne("DocSequence.Api.Entities.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_GeneratedDocuments_DocumentTypes");

                    b.Navigation("DocumentType");
                });
#pragma warning restore 612, 618
        }
    }
}
